if(NYKDTB_BUILD_TESTING)
    if (MSVC)
        message(FATAL_ERROR "Coverage instrumentation for MSVC compiler unknown")
    else()
        if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
            add_compile_options(-fprofile-instr-generate -fcoverage-mapping)
            add_link_options(-fprofile-instr-generate -fcoverage-mapping)
        elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
            add_compile_options(-fprofile-arcs -ftest-coverage)
            add_link_options(-fprofile-arcs -ftest-coverage)
        else()
            message(FATAL_ERROR "Coverage instrumentation for current compiler unknown")
        endif()
    endif()
endif()